### ISSUE TITLE
Can't upload reports when using docker-compose from git clone

### ISSUE THREAD

**Issue by jocelynjyl** [center-for-threat-informed-defense/tram#200]
Hi,

If I follow the installation instructions in the wiki and use curl to fetch the docker-compose.yml, then continue with docker-compose up, everything works as expected. 

However, if I git clone and then navigate to the docker folder, then run docker-compose up, I cannot upload any files. 

I've tested with the same PDF file, and it works with the docker-compose fetched by curl but not the git clone. I've also deleted the local copy of tram and pulled a fresh copy. I'm running it on a Mac with the Intel chip. 

Any ideas why this happens and how to fix it? Thanks!

The error log I get from the git cloned version when I try to upload a file is as follows: 
```
docker-tram-1   | Traceback (most recent call last):
docker-tram-1   |   File "/tram/src/tram/ml/base.py", line 514, in run_model
docker-tram-1   |     report = self.model.process_job(job)
docker-tram-1   |   File "/tram/src/tram/ml/base.py", line 420, in process_job
docker-tram-1   |     df = self.predict_samples(samples)
docker-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
docker-tram-1   |     return func(*args, **kwargs)
docker-tram-1   |   File "/tram/src/tram/ml/base.py", line 372, in predict_samples
docker-tram-1   |     tokenizer = AutoTokenizer.from_pretrained("/tram/data/priv-allenai-scibert-scivocab-uncased")
docker-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
docker-tram-1   |     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
docker-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
docker-tram-1   |     resolved_config_file = cached_file(
docker-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/transformers/utils/hub.py", line 417, in cached_file
docker-tram-1   |     resolved_file = hf_hub_download(
docker-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
docker-tram-1   |     validate_repo_id(arg_value)
docker-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
docker-tram-1   |     raise HFValidationError(
docker-tram-1   | huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/tram/data/priv-allenai-scibert-scivocab-uncased'. Use `repo_type` argument if needed.
```

**Comment by jocelynjyl** [comment]
Thanks for the speedy reply! Everything is working after downloading the pre-trained BERT model.
